unpackaged/objects/Camping_Item__c.object
<CustomObject>
    <fields>
        <fullName>Packed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Packed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Camping Item</label>
    <nameField>
        <label>Camping Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Camping_Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/CampingListController.cls
public  class CampingListController {

	@AuraEnabled
	public static void saveItem (Camping_Item__c campingItem) {
		try{
			insert campingItem;
		}catch (Exception e){
			System.debug(e.getMessage());
		}

	}

	@AuraEnabled
	public static List<Camping_Item__c> getItems() {
		List<Camping_Item__c> campingItems = [SELECT Id,Name,Price__c,Packed__c,Quantity__c FROM Camping_Item__c];
		return campingItems;
	}


}