unpackaged/objects/Car__c.object
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Car__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Car</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Car__c.IsValidForRent__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Car__c</referenceTo>
        <relationshipName>Rends</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>EndDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <defaultValue>today()</defaultValue>
        <label>StartDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/ControllerRelatedDeals.cls
/**
 * Created by dkachanovskyi on 12/31/2018.
 */
public with sharing class ControllerRelatedDeals {

	private Id carId;
	private static final String STATUS_OPEN = 'Open';
	public ControllerRelatedDeals(ApexPages.StandardController stdController) {
		carId = stdController.getId();
	}

	public List<Deal__c> relatedDeals {

		get{
			relatedDeals = [SELECT Car__c, StartDate__c, EndDate__c, Status__c
					FROM Deal__c
					WHERE Car__c = :carId
			AND Status__c =: STATUS_OPEN];
			return relatedDeals;
		}
		set;
	}

	@AuraEnabled
	public static List<Deal__c> getAuraRelatedDeals(Id carId) {
		Set<Id> carIds = new Set<Id>();
		carIds.add(carId);
		Set<String> fields = new Set<String>();
		fields.add('Status__c');
		fields.add('StartDate__c');
		fields.add('EndDate__c');
		fields.add('Car__c');

		List<Deal__c> relatedDeals = new List<Deal__c>();
		relatedDeals = CarRentDAO.relatedDeals(fields,STATUS_OPEN, carIds);
		return relatedDeals;
	}

}