unpackaged/objects/Car__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sedan</fullName>
                </value>
                <value>
                    <fullName>Minivan</fullName>
                </value>
                <value>
                    <fullName>Hatchback</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Car</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Car__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Car</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Car__c.IsValidForRent__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Car__c</referenceTo>
        <relationshipName>Rends</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>EndDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_Manager__c</fullName>
        <label>Sales Manager</label>
        <referenceTo>Sales__c</referenceTo>
        <relationshipName>Rends</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <defaultValue>today()</defaultValue>
        <label>StartDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Sales__c.object
<CustomObject>
    <label>Sales Manager</label>
    <nameField>
        <label>Sales  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Manegers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

out/production/WorkTask/objects/validWord__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Word__c</fullName>
        <label>Word</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Restricted word in name</label>
</CustomObject>

unpackaged/classes/ControllerForDealsTest.cls
/**
 * Created by dkachanovskyi on 1/2/2019.
 */

@IsTest
public class ControllerForDealsTest {

    private static List<Deal__c> existingDeals = new List<Deal__c>();
//  private static List<Deal__c> newDeals = new List<Deal__c>();
    private static List<Car__c> idCars =new List<Car__c>();
    private static ApexPages.StandardController sc;
    public static ControllerRelatedDeals controller;

    private static void setup(Integer c) {

        validWord__c csToInsertVW = new validWord__c(Word__c = DealHandler.DEFAULT_STATUS);
        insert csToInsertVW;

        Sales__c salesManager = new Sales__c(Name = 'TestName');
        insert salesManager;

        Car__c carId = new Car__c(Name = 'Opel', Type__c = 'sedan');
        insert carId;
        idCars.add(carId);


        sc = new ApexPages.StandardController(carId);
        controller = new ControllerRelatedDeals(sc);


        if (c == 0) {
            for (integer i = 0;i < 5;i++) {
                Deal__c deal = new Deal__c(Sales_Manager__c = salesManager.Id, Status__c = 'Open',
                        StartDate__c = System.today().addDays(-2),
                        EndDate__c = System.today().addDays(-1),
                        Car__c = carId.Id);
                existingDeals.add(deal);
            }
                insert existingDeals;
        }
        if(c == 1){
            for (integer i = 0;i < 5;i++) {
                Deal__c deal = new Deal__c(Sales_Manager__c = salesManager.Id, Status__c = 'Open',
                        StartDate__c = System.today().addDays(-2),
                        EndDate__c = System.today().addDays(-1),
                        Car__c = carId.Id);
                existingDeals.add(deal);
            }
        }
    }
    @isTest static void TestProcessDisplayAllDealsSuccess() {
        setup(0);
        Test.startTest();
        existingDeals = controller.relatedDeals;
        Test.stopTest();
        System.assert(existingDeals.size()<= 5);
    }

    @isTest static void TestProcessDisplayAllDealsFail(){
        setup(1);
        Test.startTest();
        try{
            existingDeals = controller.relatedDeals;
        }catch (Exception e){
            System.debug(e);
        }
        Test.stopTest();
    }
}