unpackaged/objects/Car__c.object
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Car__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Car</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Car__c.IsValidForRent__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Car__c</referenceTo>
        <relationshipName>Rends</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/CarHandler.cls
/**
 * Created by dkachanovskyi on 12/5/2018.
 */
public class CarHandler {
	public void processBeforeDelete(Map<Id, Car__c> oldTrigger){
		updateDeal(oldTrigger);
	}


	private void updateDeal(Map<Id, Car__c> triggerOld){

		List<Deal__c> relatedDeals = [SELECT id, Deal__c.Status__c
		FROM Deal__c
				WHERE Status__c = 'Open'
		AND Car__c	IN : triggerOld.keySet()];

		for(Deal__c deal: relatedDeals){
			if(deal.Status__c == 'Open'){
				deal.Status__c = 'Lost';
			}
		}
		update relatedDeals;
	}


}