unpackaged/objects/Car__c.object
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Car__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Car</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Car__c.IsValidForRent__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Car__c</referenceTo>
        <relationshipName>Rends</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/CarRentDAO.cls
public class CarRentDAO {

    public List<Deal__c> getWonDeals(DateTime StartDate, DateTime EndDate){
        List<Deal__c> listDeal = new List<Deal__c>();
        for(Deal__c deal:listDeal){
            if(StartDate != EndDate && deal.Status__c == 'Won'){
                listDeal.add(deal);
            }
        }
        return listDeal;
    }
    
    public Map<Id,Integer> getWonDealsBySalesRepIds (Set<Id> salesReplds){
        Map<Id,Integer> mapRepAndWon = new Map<Id, Integer>();
        return mapRepAndWon;
    }
    public List<Car__c> getCarsAvailableForRent(Date rentStart, Date rentEnd){
        List<Car__c> listCar = new List<Car__c>();
        for(Car__c car : listCar){
            
        }
        return listCar;
    }
   // public Map<Id, Integer> getCarRentStatistic(){
    //    
  //  }
   // public SalesRepresentative__c getTopRatedSalesRepOfYear(Id carId){
   //     
   // }
}