unpackaged/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>EndDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/CarDealServices.cls
public class CarDealServices {

    public List<Deal__c>  filterFinished(){
        List<Deal__c> deal = new List<Deal__c>();
        for(Deal__c d : deal){
            if(d.Status__c == 'Won'|| d.Status__c == 'Lost'){
                deal.add(d);
            }
        }
        return deal;
    }
    public void setEndDate(){
        List<Deal__c> deals = new List<Deal__c>();
        for(Deal__c deal : deals){
            deal.EndDate__c = System.today();
        }
    }
    
}